services:
  frontend:
    build: ./fe
    volumes:
      - ./fe:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev

  backend:
    build: ./be
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://100.93.79.71:3306/db
      - SPRING_DATASOURCE_USERNAME=cvip
      - SPRING_DATASOURCE_PASSWORD=roadtowf
    volumes:
      - ./uploaded-videos:/app/videos