services:
  frontend:
    build: 
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=https://hcmiu-project-web.id.vn/api
    command: npm run build && npm run preview

  backend:
    build: 
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SPRING_DATASOURCE_URL=jdbc:mysql://100.93.79.71:3306/db
      - SPRING_DATASOURCE_USERNAME=cvip
      - SPRING_DATASOURCE_PASSWORD=cvip
    volumes:
      - ./uploaded-videos:/app/videos

  # Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
