services:
  frontend:
    build: ./fe
    volumes:
      - ./fe:/app
      - /app/node_modules  # Prevents overwriting container’s node_modules with an empty host folder
    ports:
      - "5173:5173"
    command: npm run dev

  backend:
    build: ./be
    volumes:
      - ./be:/app
    ports:
      - "8080:8080"
    command: mvn spring-boot:run
    environment:
      # Optional: triggers Spring Boot DevTools restart if using this feature
      SPRING_DEVTOOLS_RESTART_TRIGGER_FILE: .restart
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: cvip
      MYSQL_DATABASE: db
      MYSQL_USER: cvip
      MYSQL_PASSWORD: cvip
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  mysql_data: